# Generated by Django 3.1.7 on 2021-04-19 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210419_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerary',
            name='description',
            field=models.TextField(blank=True, default='', max_length=500),
        ),
    ]
