# Generated by Django 3.1.7 on 2021-04-23 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210421_1008'),
        ('api', '0003_auto_20210419_1147'),
    ]

    operations = [
    ]
