# Generated by Django 3.1.7 on 2021-04-26 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_merge_20210423_0905'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='duration_unit',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='description',
            field=models.TextField(default='', max_length=500),
        ),
    ]
