# Generated by Django 3.1.7 on 2021-04-30 15:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0005_auto_20210426_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='rating',
        ),
        migrations.AddField(
            model_name='itinerary',
            name='username',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='duration_unit',
            field=models.TextField(choices=[('Day', 'Day'), ('Week', 'Week'), ('Month', 'Month')], default=''),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='user',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.TextField(blank=True, default='', max_length=500),
        ),
    ]
