# Generated by Django 3.1.7 on 2021-04-30 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210430_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerary',
            name='duration_unit',
            field=models.TextField(choices=[('Day(s)', 'Day'), ('Week(s)', 'Week'), ('Month(s)', 'Month')], default=''),
        ),
    ]
